<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\OrdersController;
use App\Http\Controllers\Admin\CustomersController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\ProductsController;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\ProductFamiliesController;
use App\Http\Controllers\Admin\ReturnsController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'role.admin_or_manager'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard-stats', [DashboardController::class, 'stats'])->name('dashboard.stats');
    Route::get('/orders', [OrdersController::class, 'index'])->name('orders');
    Route::get('/orders/{orderNumber}', [OrdersController::class, 'show'])->name('orders.show');
    Route::get('/orders/{orderNumber}/edit', [OrdersController::class, 'edit'])->name('orders.edit');
    Route::put('/orders/{orderNumber}', [OrdersController::class, 'update'])->name('orders.update');
    Route::put('/orders/{orderNumber}/batch-update', [OrdersController::class, 'batchUpdate'])->name('orders.batch-update');
    Route::post('/orders/{orderNumber}/mark-as-paid', [OrdersController::class, 'markAsPaid'])->name('orders.mark-as-paid');
    Route::post('/orders/{orderNumber}/mark-as-unpaid', [OrdersController::class, 'markAsUnpaid'])->name('orders.mark-as-unpaid');
    Route::get('/customers', [CustomersController::class, 'index'])->name('customers');
    Route::get('/customers/{id}', [CustomersController::class, 'show'])->name('customers.show');
    Route::post('/customers/deactivate', [CustomersController::class, 'deactivate'])->name('customers.deactivate');
    Route::post('/customers/activate', [CustomersController::class, 'activate'])->name('customers.activate');
    Route::get('/users', [UsersController::class, 'index'])->name('users');
    Route::post('/users/deactivate', [UsersController::class, 'deactivate'])->name('users.deactivate');
    Route::post('/users/activate', [UsersController::class, 'activate'])->name('users.activate');
    Route::get('/products', [ProductsController::class, 'index'])->name('products');
    Route::get('/products/{id}', [ProductsController::class, 'show'])->name('products.show');
    Route::put('/products/{id}', [ProductsController::class, 'update'])->name('products.update');
    Route::post('/products/{id}/images', [ProductsController::class, 'storeImage'])->name('products.images.store');
    Route::post('/products/{id}/variants', [ProductsController::class, 'syncVariants'])->name('products.variants.sync');
    Route::get('/categories', [CategoriesController::class, 'index'])->name('categories');
    Route::get('/categories/{id}', [CategoriesController::class, 'show'])->name('categories.show');
    Route::put('/categories/{id}', [CategoriesController::class, 'update'])->name('categories.update');
    Route::delete('/categories/{id}', [CategoriesController::class, 'destroy'])->name('categories.destroy');
    Route::post('/categories/deactivate', [CategoriesController::class, 'deactivate'])->name('categories.deactivate');
    Route::post('/categories/activate', [CategoriesController::class, 'activate'])->name('categories.activate');
    Route::get('/product-families', [ProductFamiliesController::class, 'index'])->name('product-families');
    Route::get('/product-families/{id}', [ProductFamiliesController::class, 'show'])->name('product-families.show');
    Route::post('/product-families/deactivate', [ProductFamiliesController::class, 'deactivate'])->name('product-families.deactivate');
    Route::post('/product-families/activate', [ProductFamiliesController::class, 'activate'])->name('product-families.activate');
    Route::get('/returns', [ReturnsController::class, 'index'])->name('returns');
    Route::get('/returns/{id}', [ReturnsController::class, 'show'])->name('returns.show');
    Route::put('/returns/{id}/status', [ReturnsController::class, 'updateStatus'])->name('returns.update-status');
    Route::put('/returns/{id}/refund-amount', [ReturnsController::class, 'updateRefundAmount'])->name('returns.update-refund-amount');
    Route::put('/returns/{id}/restock-item', [ReturnsController::class, 'updateRestockItem'])->name('returns.update-restock-item');
});
