<?php

namespace Database\Seeders\Develop;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Products Seeder
 * 
 * Dummy/Test Data - Development Only
 * 
 * Seeds products for development/testing.
 * Contains a large array of product data (gaming laptops, business laptops, smartphones, tablets, etc.)
 * 
 * Depends on: BrandsSeeder (must run before ProductsSeeder)
 */
class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Seeding products...');
        $this->seedProducts();
        $this->command->info('✓ Products seeded successfully');
    }

    private function seedProducts(): void
    {
        // Get brands mapping
        $brands = DB::table('brands')->pluck('id', 'slug')->toArray();
        
        if (empty($brands)) {
            $this->command->warn('⚠️  No brands found. Please run BrandsSeeder first.');
        }

        $products = $this->getProductData();

        foreach ($products as $product) {
            // Detect brand from product name
            $brandId = $this->detectBrandId($product['name'], $brands);
            
            $productData = array_merge($product, [
                'brand_id' => $brandId,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            DB::table('products')->updateOrInsert(
                ['sku' => $product['sku']],
                $productData
            );
        }
    }

    /**
     * Detect brand ID from product name.
     * 
     * @param string $productName
     * @param array $brands Array of ['slug' => 'id'] mappings
     * @return int|null
     */
    private function detectBrandId(string $productName, array $brands): ?int
    {
        // Brand name to slug mapping
        $brandMapping = [
            'asus' => 'asus',
            'lenovo' => 'lenovo',
            'acer' => 'acer',
            'apple' => 'apple',
            'dell' => 'dell',
            'hp' => 'hp',
            'samsung' => 'samsung',
            'google' => 'google',
            'pixel' => 'google',
            'oneplus' => 'oneplus',
            'xiaomi' => 'xiaomi',
            'sony' => 'sony',
            'canon' => 'canon',
            'nikon' => 'nikon',
            'microsoft' => 'microsoft',
            'xbox' => 'microsoft',
            'nike' => 'nike',
            'adidas' => 'adidas',
            'lg' => 'lg',
            'huawei' => 'huawei',
            'motorola' => 'motorola',
            'nokia' => 'nokia',
        ];

        $productNameLower = mb_strtolower($productName);

        foreach ($brandMapping as $keyword => $slug) {
            if (str_contains($productNameLower, $keyword) && isset($brands[$slug])) {
                return $brands[$slug];
            }
        }

        return null;
    }

    /**
     * Get product data array.
     * Contains the full product array extracted from DevelopmentSeeder.
     */
    private function getProductData(): array
    {
        $products = [

            // Gaming Laptops
            [
                'sku' => 'LAP-GAM-001',
                'ean' => '1234567890123',
                'model' => 'Gaming Pro 15',
                'name' => 'Laptop Gaming ASUS ROG Strix G15',
                'description' => 'Laptop gaming performant cu procesor AMD Ryzen 9 si placa video NVIDIA RTX 4070. Perfect pentru gaming si streaming.',
                'short_description' => 'Laptop gaming de top cu RTX 4070',
                'price_ron' => 8999.99,
                'purchase_price_ron' => 6500.00,
                'stock_quantity' => 15,
                'weight' => 2.5,
                'length' => 35.0,
                'width' => 25.0,
                'height' => 2.5,
                'main_image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'LAP-GAM-002',
                'ean' => '1234567890128',
                'model' => 'Legion 5 Pro',
                'name' => 'Lenovo Legion 5 Pro 16" RTX 4060',
                'description' => 'Laptop gaming cu ecran QHD 165Hz, procesor AMD Ryzen 7 si RTX 4060. Ideal pentru gaming competitiv.',
                'short_description' => 'Laptop gaming Legion cu RTX 4060',
                'price_ron' => 7499.99,
                'purchase_price_ron' => 5800.00,
                'stock_quantity' => 12,
                'weight' => 2.6,
                'length' => 35.6,
                'width' => 26.4,
                'height' => 2.6,
                'main_image_url' => 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'LAP-GAM-003',
                'ean' => '1234567890129',
                'model' => 'Predator Helios',
                'name' => 'Acer Predator Helios 16 RTX 4080',
                'description' => 'Laptop gaming premium cu RTX 4080, procesor Intel Core i9 si ecran 16" QHD.',
                'short_description' => 'Laptop gaming premium cu RTX 4080',
                'price_ron' => 12999.99,
                'purchase_price_ron' => 9800.00,
                'stock_quantity' => 8,
                'weight' => 2.8,
                'length' => 36.0,
                'width' => 28.0,
                'height' => 2.7,
                'main_image_url' => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Business Laptops
            [
                'sku' => 'LAP-BUS-001',
                'ean' => '1234567890126',
                'model' => 'ThinkPad X1 Carbon',
                'name' => 'Lenovo ThinkPad X1 Carbon Gen 11',
                'description' => 'Laptop business ultraportabil cu procesor Intel Core i7, perfect pentru profesionisti.',
                'short_description' => 'Laptop business ultraportabil',
                'price_ron' => 6999.99,
                'purchase_price_ron' => 5500.00,
                'stock_quantity' => 10,
                'weight' => 1.12,
                'length' => 31.5,
                'width' => 22.2,
                'height' => 1.55,
                'main_image_url' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'LAP-BUS-002',
                'ean' => '1234567890130',
                'model' => 'MacBook Pro 14',
                'name' => 'Apple MacBook Pro 14" M3 Pro',
                'description' => 'Laptop profesional Apple cu chip M3 Pro, ecran Liquid Retina XDR si performanta exceptionala.',
                'short_description' => 'MacBook Pro 14" cu chip M3 Pro',
                'price_ron' => 12999.99,
                'purchase_price_ron' => 10500.00,
                'stock_quantity' => 6,
                'weight' => 1.6,
                'length' => 31.26,
                'width' => 22.12,
                'height' => 1.55,
                'main_image_url' => 'https://images.unsplash.com/photo-1517336714731-4896893a3f8f?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'LAP-BUS-003',
                'ean' => '1234567890131',
                'model' => 'Dell XPS 13',
                'name' => 'Dell XPS 13 Plus Intel i7',
                'description' => 'Laptop ultraportabil cu ecran OLED 13.4", procesor Intel Core i7 si design premium.',
                'short_description' => 'Dell XPS 13 Plus ultraportabil',
                'price_ron' => 7999.99,
                'purchase_price_ron' => 6200.00,
                'stock_quantity' => 9,
                'weight' => 1.26,
                'length' => 29.57,
                'width' => 19.87,
                'height' => 1.5,
                'main_image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Smartphones
            [
                'sku' => 'PHONE-001',
                'ean' => '1234567890124',
                'model' => 'iPhone 15 Pro',
                'name' => 'iPhone 15 Pro 256GB',
                'description' => 'Cel mai recent iPhone cu procesor A17 Pro, camera profesionala si design din titan.',
                'short_description' => 'iPhone 15 Pro 256GB',
                'price_ron' => 5999.99,
                'purchase_price_ron' => 4800.00,
                'stock_quantity' => 25,
                'weight' => 0.187,
                'length' => 15.9,
                'width' => 7.6,
                'height' => 0.83,
                'main_image_url' => 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'PHONE-002',
                'ean' => '1234567890125',
                'model' => 'Samsung Galaxy S24',
                'name' => 'Samsung Galaxy S24 Ultra 512GB',
                'description' => 'Smartphone flagship cu S Pen, camera de 200MP si ecran Dynamic AMOLED 2X.',
                'short_description' => 'Galaxy S24 Ultra cu S Pen',
                'price_ron' => 5499.99,
                'purchase_price_ron' => 4400.00,
                'stock_quantity' => 20,
                'weight' => 0.233,
                'length' => 16.2,
                'width' => 7.9,
                'height' => 0.88,
                'main_image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'PHONE-003',
                'ean' => '1234567890132',
                'model' => 'Pixel 8 Pro',
                'name' => 'Google Pixel 8 Pro 256GB',
                'description' => 'Smartphone Google cu camera AI, procesor Tensor G3 si Android pur.',
                'short_description' => 'Google Pixel 8 Pro cu AI',
                'price_ron' => 4999.99,
                'purchase_price_ron' => 4000.00,
                'stock_quantity' => 18,
                'weight' => 0.213,
                'length' => 16.25,
                'width' => 7.65,
                'height' => 0.88,
                'main_image_url' => 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'PHONE-004',
                'ean' => '1234567890133',
                'model' => 'OnePlus 12',
                'name' => 'OnePlus 12 256GB',
                'description' => 'Smartphone flagship cu Snapdragon 8 Gen 3, camera Hasselblad si incarcare rapida 100W.',
                'short_description' => 'OnePlus 12 cu Snapdragon 8 Gen 3',
                'price_ron' => 4499.99,
                'purchase_price_ron' => 3600.00,
                'stock_quantity' => 15,
                'weight' => 0.220,
                'length' => 16.43,
                'width' => 7.56,
                'height' => 0.92,
                'main_image_url' => 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'PHONE-005',
                'ean' => '1234567890134',
                'model' => 'Xiaomi 14',
                'name' => 'Xiaomi 14 Pro 512GB',
                'description' => 'Smartphone premium cu Snapdragon 8 Gen 3, camera Leica si ecran LTPO AMOLED.',
                'short_description' => 'Xiaomi 14 Pro cu Leica',
                'price_ron' => 3999.99,
                'purchase_price_ron' => 3200.00,
                'stock_quantity' => 22,
                'weight' => 0.209,
                'length' => 16.1,
                'width' => 7.5,
                'height' => 0.85,
                'main_image_url' => 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Tablets
            [
                'sku' => 'TAB-001',
                'ean' => '1234567890135',
                'model' => 'iPad Pro 12.9',
                'name' => 'Apple iPad Pro 12.9" M2 256GB',
                'description' => 'Tableta profesionala cu chip M2, ecran Liquid Retina XDR si suport pentru Apple Pencil.',
                'short_description' => 'iPad Pro 12.9" cu chip M2',
                'price_ron' => 6999.99,
                'purchase_price_ron' => 5600.00,
                'stock_quantity' => 14,
                'weight' => 0.682,
                'length' => 28.06,
                'width' => 21.5,
                'height' => 0.64,
                'main_image_url' => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'TAB-002',
                'ean' => '1234567890136',
                'model' => 'Galaxy Tab S9',
                'name' => 'Samsung Galaxy Tab S9 Ultra 256GB',
                'description' => 'Tableta Android premium cu ecran AMOLED 14.6", procesor Snapdragon 8 Gen 2 si S Pen inclus.',
                'short_description' => 'Galaxy Tab S9 Ultra cu S Pen',
                'price_ron' => 5999.99,
                'purchase_price_ron' => 4800.00,
                'stock_quantity' => 11,
                'weight' => 0.732,
                'length' => 32.64,
                'width' => 20.88,
                'height' => 0.55,
                'main_image_url' => 'https://images.unsplash.com/photo-1561154464-82e9adf32750?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Headphones
            [
                'sku' => 'HEAD-001',
                'ean' => '1234567890137',
                'model' => 'AirPods Pro 2',
                'name' => 'Apple AirPods Pro 2',
                'description' => 'Casti wireless cu cancelare activa a zgomotului, audio spatial si rezistenta la apa.',
                'short_description' => 'AirPods Pro 2 cu ANC',
                'price_ron' => 1299.99,
                'purchase_price_ron' => 950.00,
                'stock_quantity' => 50,
                'weight' => 0.056,
                'length' => 6.0,
                'width' => 2.4,
                'height' => 2.4,
                'main_image_url' => 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'HEAD-002',
                'ean' => '1234567890138',
                'model' => 'Sony WH-1000XM5',
                'name' => 'Sony WH-1000XM5 Wireless',
                'description' => 'Casti over-ear cu cancelare activa a zgomotului, baterie 30h si calitate audio Hi-Res.',
                'short_description' => 'Sony WH-1000XM5 cu ANC',
                'price_ron' => 1999.99,
                'purchase_price_ron' => 1500.00,
                'stock_quantity' => 30,
                'weight' => 0.250,
                'length' => 20.0,
                'width' => 18.0,
                'height' => 8.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Smartwatches
            [
                'sku' => 'WATCH-001',
                'ean' => '1234567890139',
                'model' => 'Apple Watch Ultra 2',
                'name' => 'Apple Watch Ultra 2 GPS',
                'description' => 'Smartwatch premium pentru sport cu ecran Always-On, GPS precis si rezistenta extrema.',
                'short_description' => 'Apple Watch Ultra 2 pentru sport',
                'price_ron' => 4499.99,
                'purchase_price_ron' => 3600.00,
                'stock_quantity' => 20,
                'weight' => 0.061,
                'length' => 4.9,
                'width' => 4.9,
                'height' => 1.4,
                'main_image_url' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'WATCH-002',
                'ean' => '1234567890140',
                'model' => 'Galaxy Watch 6',
                'name' => 'Samsung Galaxy Watch 6 Classic 47mm',
                'description' => 'Smartwatch Android cu ecran rotativ, monitorizare sanatate avansata si baterie de lunga durata.',
                'short_description' => 'Galaxy Watch 6 Classic',
                'price_ron' => 1999.99,
                'purchase_price_ron' => 1500.00,
                'stock_quantity' => 25,
                'weight' => 0.059,
                'length' => 4.7,
                'width' => 4.7,
                'height' => 1.3,
                'main_image_url' => 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Cameras
            [
                'sku' => 'CAM-001',
                'ean' => '1234567890141',
                'model' => 'Canon EOS R6',
                'name' => 'Canon EOS R6 Mark II Body',
                'description' => 'Camera mirrorless full-frame cu sensor 24MP, stabilizare 5-axa si filmare 4K 60fps.',
                'short_description' => 'Canon EOS R6 Mark II mirrorless',
                'price_ron' => 12999.99,
                'purchase_price_ron' => 10000.00,
                'stock_quantity' => 8,
                'weight' => 0.670,
                'length' => 13.8,
                'width' => 9.8,
                'height' => 8.4,
                'main_image_url' => 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'CAM-002',
                'ean' => '1234567890142',
                'model' => 'Sony A7 IV',
                'name' => 'Sony Alpha A7 IV Body',
                'description' => 'Camera mirrorless full-frame cu sensor 33MP, autofocus rapid si filmare 4K.',
                'short_description' => 'Sony Alpha A7 IV full-frame',
                'price_ron' => 11999.99,
                'purchase_price_ron' => 9500.00,
                'stock_quantity' => 10,
                'weight' => 0.658,
                'length' => 13.1,
                'width' => 9.6,
                'height' => 9.6,
                'main_image_url' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Clothing - Men's T-shirts
            [
                'sku' => 'TSHIRT-001',
                'ean' => '1234567890127',
                'model' => 'Classic T-Shirt',
                'name' => 'Tricou Barbati Basic Alb',
                'description' => 'Tricou clasic din bumbac 100%, confortabil si versatil.',
                'short_description' => 'Tricou basic alb pentru barbati',
                'price_ron' => 49.99,
                'purchase_price_ron' => 20.00,
                'stock_quantity' => 100,
                'weight' => 0.2,
                'length' => 30.0,
                'width' => 25.0,
                'height' => 2.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'TSHIRT-002',
                'ean' => '1234567890143',
                'model' => 'Premium T-Shirt',
                'name' => 'Tricou Barbati Premium Negru',
                'description' => 'Tricou premium din bumbac organic, design modern si confortabil.',
                'short_description' => 'Tricou premium negru pentru barbati',
                'price_ron' => 79.99,
                'purchase_price_ron' => 35.00,
                'stock_quantity' => 80,
                'weight' => 0.22,
                'length' => 31.0,
                'width' => 26.0,
                'height' => 2.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'TSHIRT-003',
                'ean' => '1234567890144',
                'model' => 'Polo Shirt',
                'name' => 'Polo Barbati Albastru',
                'description' => 'Polo clasic cu guler, perfect pentru casual si business casual.',
                'short_description' => 'Polo albastru pentru barbati',
                'price_ron' => 129.99,
                'purchase_price_ron' => 55.00,
                'stock_quantity' => 60,
                'weight' => 0.25,
                'length' => 32.0,
                'width' => 27.0,
                'height' => 2.5,
                'main_image_url' => 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Men's Jeans
            [
                'sku' => 'JEANS-001',
                'ean' => '1234567890145',
                'model' => 'Classic Jeans',
                'name' => 'Jeans Barbati Clasic Albastru',
                'description' => 'Jeans clasic din denim, fit regulat, confortabil si durabil.',
                'short_description' => 'Jeans clasic albastru pentru barbati',
                'price_ron' => 299.99,
                'purchase_price_ron' => 120.00,
                'stock_quantity' => 70,
                'weight' => 0.8,
                'length' => 110.0,
                'width' => 40.0,
                'height' => 3.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'JEANS-002',
                'ean' => '1234567890146',
                'model' => 'Slim Jeans',
                'name' => 'Jeans Barbati Slim Negru',
                'description' => 'Jeans fit slim, modern si elegant, perfect pentru stil casual.',
                'short_description' => 'Jeans slim negru pentru barbati',
                'price_ron' => 329.99,
                'purchase_price_ron' => 135.00,
                'stock_quantity' => 55,
                'weight' => 0.75,
                'length' => 108.0,
                'width' => 38.0,
                'height' => 3.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Women's Clothing
            [
                'sku' => 'DRESS-001',
                'ean' => '1234567890147',
                'model' => 'Summer Dress',
                'name' => 'Rochia Femei Vara Floral',
                'description' => 'Rochia eleganta cu print floral, perfecta pentru sezonul cald.',
                'short_description' => 'Rochia vara floral pentru femei',
                'price_ron' => 199.99,
                'purchase_price_ron' => 80.00,
                'stock_quantity' => 45,
                'weight' => 0.3,
                'length' => 95.0,
                'width' => 40.0,
                'height' => 2.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'BLOUSE-001',
                'ean' => '1234567890148',
                'model' => 'Elegant Blouse',
                'name' => 'Bluza Femei Eleganta Alba',
                'description' => 'Bluza eleganta din material premium, perfecta pentru birou sau evenimente.',
                'short_description' => 'Bluza eleganta alba pentru femei',
                'price_ron' => 179.99,
                'purchase_price_ron' => 75.00,
                'stock_quantity' => 50,
                'weight' => 0.25,
                'length' => 65.0,
                'width' => 45.0,
                'height' => 2.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Furniture
            [
                'sku' => 'FURN-001',
                'ean' => '1234567890149',
                'model' => 'Office Chair',
                'name' => 'Scaun Birou Ergonom',
                'description' => 'Scaun birou ergonom cu suport lombar, reglabil in inaltime si brate.',
                'short_description' => 'Scaun birou ergonom',
                'price_ron' => 899.99,
                'purchase_price_ron' => 450.00,
                'stock_quantity' => 25,
                'weight' => 15.0,
                'length' => 65.0,
                'width' => 65.0,
                'height' => 120.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'FURN-002',
                'ean' => '1234567890150',
                'model' => 'Desk Table',
                'name' => 'Birou Modern 120cm',
                'description' => 'Birou modern din lemn masiv, cu sertare si design minimalist.',
                'short_description' => 'Birou modern 120cm',
                'price_ron' => 1299.99,
                'purchase_price_ron' => 650.00,
                'stock_quantity' => 15,
                'weight' => 25.0,
                'length' => 120.0,
                'width' => 60.0,
                'height' => 75.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Kitchen
            [
                'sku' => 'KIT-001',
                'ean' => '1234567890151',
                'model' => 'Coffee Maker',
                'name' => 'Aparat Cafea Espresso Automat',
                'description' => 'Aparat de cafea espresso automat cu moara integrata si spuma de lapte.',
                'short_description' => 'Aparat cafea espresso automat',
                'price_ron' => 2499.99,
                'purchase_price_ron' => 1500.00,
                'stock_quantity' => 12,
                'weight' => 8.5,
                'length' => 35.0,
                'width' => 45.0,
                'height' => 50.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'KIT-002',
                'ean' => '1234567890152',
                'model' => 'Blender',
                'name' => 'Blender Puternic 1500W',
                'description' => 'Blender profesional cu motor 1500W, perfect pentru smoothie-uri si supe.',
                'short_description' => 'Blender puternic 1500W',
                'price_ron' => 599.99,
                'purchase_price_ron' => 300.00,
                'stock_quantity' => 30,
                'weight' => 3.2,
                'length' => 20.0,
                'width' => 20.0,
                'height' => 45.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Sports - Fitness
            [
                'sku' => 'FIT-001',
                'ean' => '1234567890153',
                'model' => 'Dumbbells Set',
                'name' => 'Set Gantere Ajustabile 2x20kg',
                'description' => 'Set gantere ajustabile, perfect pentru antrenament acasa.',
                'short_description' => 'Set gantere ajustabile 2x20kg',
                'price_ron' => 799.99,
                'purchase_price_ron' => 400.00,
                'stock_quantity' => 20,
                'weight' => 40.0,
                'length' => 50.0,
                'width' => 30.0,
                'height' => 15.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'FIT-002',
                'ean' => '1234567890154',
                'model' => 'Yoga Mat',
                'name' => 'Covoras Yoga Premium',
                'description' => 'Covoras yoga premium, antiderapant si confortabil, grosime 6mm.',
                'short_description' => 'Covoras yoga premium',
                'price_ron' => 149.99,
                'purchase_price_ron' => 60.00,
                'stock_quantity' => 40,
                'weight' => 1.5,
                'length' => 183.0,
                'width' => 61.0,
                'height' => 0.6,
                'main_image_url' => 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Running
            [
                'sku' => 'RUN-001',
                'ean' => '1234567890155',
                'model' => 'Running Shoes',
                'name' => 'Adidasi Alergare Nike Air Max',
                'description' => 'Adidasi de alergare cu tehnologie Air Max, confort si amortizare superioara.',
                'short_description' => 'Adidasi alergare Nike Air Max',
                'price_ron' => 699.99,
                'purchase_price_ron' => 350.00,
                'stock_quantity' => 35,
                'weight' => 0.8,
                'length' => 30.0,
                'width' => 12.0,
                'height' => 12.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-002',
                'ean' => '1234567890156',
                'model' => 'Adidas Ultraboost',
                'name' => 'Adidasi Alergare Adidas Ultraboost 23',
                'description' => 'Adidasi de alergare premium cu tehnologie Boost, perfect pentru alergari lungi si confort maxim.',
                'short_description' => 'Adidasi alergare Adidas Ultraboost 23',
                'price_ron' => 749.99,
                'purchase_price_ron' => 375.00,
                'stock_quantity' => 42,
                'weight' => 0.75,
                'length' => 31.0,
                'width' => 12.5,
                'height' => 12.5,
                'main_image_url' => 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-003',
                'ean' => '1234567890157',
                'model' => 'Nike Pegasus',
                'name' => 'Adidasi Alergare Nike Air Pegasus 40',
                'description' => 'Adidasi versatili de alergare cu amortizare React si design aerodinamic.',
                'short_description' => 'Adidasi alergare Nike Pegasus 40',
                'price_ron' => 649.99,
                'purchase_price_ron' => 325.00,
                'stock_quantity' => 38,
                'weight' => 0.82,
                'length' => 30.5,
                'width' => 12.2,
                'height' => 12.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-004',
                'ean' => '1234567890158',
                'model' => 'Brooks Ghost',
                'name' => 'Adidasi Alergare Brooks Ghost 15',
                'description' => 'Adidasi neutri de alergare cu amortizare DNA Loft pentru confort premium la fiecare pas.',
                'short_description' => 'Adidasi alergare Brooks Ghost 15',
                'price_ron' => 679.99,
                'purchase_price_ron' => 340.00,
                'stock_quantity' => 33,
                'weight' => 0.78,
                'length' => 30.0,
                'width' => 12.0,
                'height' => 11.8,
                'main_image_url' => 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-005',
                'ean' => '1234567890159',
                'model' => 'Asics Gel Nimbus',
                'name' => 'Adidasi Alergare Asics Gel Nimbus 25',
                'description' => 'Adidasi premium cu tehnologie Gel pentru amortizare superioara si suport excelent.',
                'short_description' => 'Adidasi alergare Asics Gel Nimbus 25',
                'price_ron' => 799.99,
                'purchase_price_ron' => 400.00,
                'stock_quantity' => 28,
                'weight' => 0.85,
                'length' => 31.0,
                'width' => 12.8,
                'height' => 12.5,
                'main_image_url' => 'https://images.unsplash.com/photo-1608667508764-33cf0726b13a?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-006',
                'ean' => '1234567890160',
                'model' => 'New Balance 1080',
                'name' => 'Adidasi Alergare New Balance Fresh Foam 1080',
                'description' => 'Adidasi cu talpa Fresh Foam X pentru amortizare si confort maxim in timpul alergarilor.',
                'short_description' => 'Adidasi alergare New Balance 1080',
                'price_ron' => 729.99,
                'purchase_price_ron' => 365.00,
                'stock_quantity' => 40,
                'weight' => 0.80,
                'length' => 30.5,
                'width' => 12.3,
                'height' => 12.2,
                'main_image_url' => 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-007',
                'ean' => '1234567890161',
                'model' => 'Saucony Triumph',
                'name' => 'Adidasi Alergare Saucony Triumph 21',
                'description' => 'Adidasi cu amortizare PWRRUN+ pentru o experienta de alergare luxoasa si confortabila.',
                'short_description' => 'Adidasi alergare Saucony Triumph 21',
                'price_ron' => 689.99,
                'purchase_price_ron' => 345.00,
                'stock_quantity' => 35,
                'weight' => 0.83,
                'length' => 31.0,
                'width' => 12.5,
                'height' => 12.3,
                'main_image_url' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-008',
                'ean' => '1234567890162',
                'model' => 'Hoka Clifton',
                'name' => 'Adidasi Alergare Hoka One One Clifton 9',
                'description' => 'Adidasi usoare cu talpa ingrosata Meta-Rocker pentru o experienta de alergare placuta.',
                'short_description' => 'Adidasi alergare Hoka Clifton 9',
                'price_ron' => 759.99,
                'purchase_price_ron' => 380.00,
                'stock_quantity' => 32,
                'weight' => 0.72,
                'length' => 30.0,
                'width' => 12.0,
                'height' => 13.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-009',
                'ean' => '1234567890163',
                'model' => 'Mizuno Wave Rider',
                'name' => 'Adidasi Alergare Mizuno Wave Rider 27',
                'description' => 'Adidasi cu tehnologie Wave pentru stabilizare si amortizare excelenta la alergare.',
                'short_description' => 'Adidasi alergare Mizuno Wave Rider 27',
                'price_ron' => 669.99,
                'purchase_price_ron' => 335.00,
                'stock_quantity' => 37,
                'weight' => 0.79,
                'length' => 30.5,
                'width' => 12.2,
                'height' => 12.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-010',
                'ean' => '1234567890164',
                'model' => 'Under Armour Hovr',
                'name' => 'Adidasi Alergare Under Armour HOVR Sonic 6',
                'description' => 'Adidasi cu tehnologie HOVR pentru returnare de energie si conectivitate smart.',
                'short_description' => 'Adidasi alergare Under Armour HOVR Sonic 6',
                'price_ron' => 719.99,
                'purchase_price_ron' => 360.00,
                'stock_quantity' => 30,
                'weight' => 0.81,
                'length' => 30.8,
                'width' => 12.4,
                'height' => 12.2,
                'main_image_url' => 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-011',
                'ean' => '1234567890165',
                'model' => 'Salomon Speedcross',
                'name' => 'Adidasi Alergare Trail Salomon Speedcross 6',
                'description' => 'Adidasi pentru alergare pe trasee cu aderenta excelenta si protectie la terenuri dificile.',
                'short_description' => 'Adidasi alergare trail Salomon Speedcross 6',
                'price_ron' => 779.99,
                'purchase_price_ron' => 390.00,
                'stock_quantity' => 25,
                'weight' => 0.88,
                'length' => 31.0,
                'width' => 13.0,
                'height' => 13.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-012',
                'ean' => '1234567890166',
                'model' => 'Reebok Floatride',
                'name' => 'Adidasi Alergare Reebok Floatride Energy 5',
                'description' => 'Adidasi usoare cu spuma Floatride pentru o experienta de alergare dinamica si confortabila.',
                'short_description' => 'Adidasi alergare Reebok Floatride Energy 5',
                'price_ron' => 649.99,
                'purchase_price_ron' => 325.00,
                'stock_quantity' => 36,
                'weight' => 0.74,
                'length' => 30.0,
                'width' => 12.0,
                'height' => 11.8,
                'main_image_url' => 'https://images.unsplash.com/photo-1605030753481-bb38b08c384a?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-013',
                'ean' => '1234567890167',
                'model' => 'Puma Velocity',
                'name' => 'Adidasi Alergare Puma Velocity Nitro 2',
                'description' => 'Adidasi cu tehnologie Nitro pentru amortizare reactiva si viteza maxima.',
                'short_description' => 'Adidasi alergare Puma Velocity Nitro 2',
                'price_ron' => 699.99,
                'purchase_price_ron' => 350.00,
                'stock_quantity' => 34,
                'weight' => 0.76,
                'length' => 30.5,
                'width' => 12.2,
                'height' => 12.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-014',
                'ean' => '1234567890168',
                'model' => 'On Cloudrunner',
                'name' => 'Adidasi Alergare On Cloudrunner',
                'description' => 'Adidasi cu tehnologie CloudTec pentru o experienta de alergare unica si confortabila.',
                'short_description' => 'Adidasi alergare On Cloudrunner',
                'price_ron' => 849.99,
                'purchase_price_ron' => 425.00,
                'stock_quantity' => 22,
                'weight' => 0.77,
                'length' => 30.8,
                'width' => 12.3,
                'height' => 12.5,
                'main_image_url' => 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-015',
                'ean' => '1234567890169',
                'model' => 'Nike Vomero',
                'name' => 'Adidasi Alergare Nike Air Zoom Vomero 17',
                'description' => 'Adidasi cu amortizare Zoom Air si React pentru confort si performanta la alergare.',
                'short_description' => 'Adidasi alergare Nike Vomero 17',
                'price_ron' => 759.99,
                'purchase_price_ron' => 380.00,
                'stock_quantity' => 31,
                'weight' => 0.84,
                'length' => 31.0,
                'width' => 12.5,
                'height' => 12.3,
                'main_image_url' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-016',
                'ean' => '1234567890170',
                'model' => 'Asics Kayano',
                'name' => 'Adidasi Alergare Asics Gel Kayano 30',
                'description' => 'Adidasi cu suport si stabilizare excelenta pentru alergatori cu pronatie sau picioare late.',
                'short_description' => 'Adidasi alergare Asics Gel Kayano 30',
                'price_ron' => 829.99,
                'purchase_price_ron' => 415.00,
                'stock_quantity' => 27,
                'weight' => 0.86,
                'length' => 31.2,
                'width' => 13.0,
                'height' => 12.8,
                'main_image_url' => 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-017',
                'ean' => '1234567890171',
                'model' => 'Brooks Glycerin',
                'name' => 'Adidasi Alergare Brooks Glycerin 21',
                'description' => 'Adidasi premium cu amortizare maxima DNA Loft v3 pentru confort maxim la alergare.',
                'short_description' => 'Adidasi alergare Brooks Glycerin 21',
                'price_ron' => 799.99,
                'purchase_price_ron' => 400.00,
                'stock_quantity' => 29,
                'weight' => 0.87,
                'length' => 31.0,
                'width' => 12.8,
                'height' => 12.5,
                'main_image_url' => 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-018',
                'ean' => '1234567890172',
                'model' => 'New Balance 880',
                'name' => 'Adidasi Alergare New Balance 880v13',
                'description' => 'Adidasi versatili cu talpa Fresh Foam pentru o experienta de alergare confortabila si stabila.',
                'short_description' => 'Adidasi alergare New Balance 880v13',
                'price_ron' => 689.99,
                'purchase_price_ron' => 345.00,
                'stock_quantity' => 33,
                'weight' => 0.81,
                'length' => 30.5,
                'width' => 12.3,
                'height' => 12.2,
                'main_image_url' => 'https://images.unsplash.com/photo-1608667508764-33cf0726b13a?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-019',
                'ean' => '1234567890173',
                'model' => 'Saucony Ride',
                'name' => 'Adidasi Alergare Saucony Ride 16',
                'description' => 'Adidasi cu talpa PWRRUN pentru o experienta de alergare echilibrata si confortabila.',
                'short_description' => 'Adidasi alergare Saucony Ride 16',
                'price_ron' => 659.99,
                'purchase_price_ron' => 330.00,
                'stock_quantity' => 38,
                'weight' => 0.78,
                'length' => 30.5,
                'width' => 12.2,
                'height' => 12.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1605030753481-bb38b08c384a?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-020',
                'ean' => '1234567890174',
                'model' => 'Nike React Infinity',
                'name' => 'Adidasi Alergare Nike React Infinity Run 4',
                'description' => 'Adidasi cu tehnologie React pentru reducerea riscului de accidentari si confort la alergare.',
                'short_description' => 'Adidasi alergare Nike React Infinity Run 4',
                'price_ron' => 789.99,
                'purchase_price_ron' => 395.00,
                'stock_quantity' => 26,
                'weight' => 0.83,
                'length' => 31.0,
                'width' => 12.5,
                'height' => 12.4,
                'main_image_url' => 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'RUN-021',
                'ean' => '1234567890175',
                'model' => 'Adidas Solarboost',
                'name' => 'Adidasi Alergare Adidas Solarboost 23',
                'description' => 'Adidasi cu suport si stabilitate pentru alergari lungi, cu tehnologie Boost pentru energia continua.',
                'short_description' => 'Adidasi alergare Adidas Solarboost 23',
                'price_ron' => 769.99,
                'purchase_price_ron' => 385.00,
                'stock_quantity' => 28,
                'weight' => 0.85,
                'length' => 31.2,
                'width' => 12.6,
                'height' => 12.5,
                'main_image_url' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Gaming Consoles
            [
                'sku' => 'CONS-001',
                'ean' => '1234567890156',
                'model' => 'PlayStation 5',
                'name' => 'Sony PlayStation 5 Console',
                'description' => 'Consola de jocuri next-gen cu SSD ultra-rapid si grafica 4K.',
                'short_description' => 'PlayStation 5 console',
                'price_ron' => 2999.99,
                'purchase_price_ron' => 2400.00,
                'stock_quantity' => 18,
                'weight' => 4.5,
                'length' => 39.0,
                'width' => 26.0,
                'height' => 10.4,
                'main_image_url' => 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'CONS-002',
                'ean' => '1234567890157',
                'model' => 'Xbox Series X',
                'name' => 'Microsoft Xbox Series X',
                'description' => 'Consola de jocuri de ultima generatie cu tehnologie Quick Resume.',
                'short_description' => 'Xbox Series X console',
                'price_ron' => 2799.99,
                'purchase_price_ron' => 2200.00,
                'stock_quantity' => 15,
                'weight' => 4.45,
                'length' => 30.1,
                'width' => 15.1,
                'height' => 15.1,
                'main_image_url' => 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Video Games
            [
                'sku' => 'GAME-001',
                'ean' => '1234567890158',
                'model' => 'Game PS5',
                'name' => 'God of War Ragnarök PS5',
                'description' => 'Joc de actiune-aventura epic pentru PlayStation 5.',
                'short_description' => 'God of War Ragnarök PS5',
                'price_ron' => 299.99,
                'purchase_price_ron' => 150.00,
                'stock_quantity' => 50,
                'weight' => 0.1,
                'length' => 17.0,
                'width' => 13.5,
                'height' => 1.5,
                'main_image_url' => 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            [
                'sku' => 'GAME-002',
                'ean' => '1234567890159',
                'model' => 'Game Xbox',
                'name' => 'Forza Horizon 5 Xbox',
                'description' => 'Joc de curse open-world pentru Xbox Series X/S.',
                'short_description' => 'Forza Horizon 5 Xbox',
                'price_ron' => 279.99,
                'purchase_price_ron' => 140.00,
                'stock_quantity' => 45,
                'weight' => 0.1,
                'length' => 17.0,
                'width' => 13.5,
                'height' => 1.5,
                'main_image_url' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Books - Fiction
            [
                'sku' => 'BOOK-001',
                'ean' => '1234567890160',
                'model' => 'Novel',
                'name' => 'Cartile lui Haruki Murakami - Set 5 volume',
                'description' => 'Set complet cu cele mai populare romane ale lui Haruki Murakami.',
                'short_description' => 'Set Murakami 5 volume',
                'price_ron' => 249.99,
                'purchase_price_ron' => 120.00,
                'stock_quantity' => 30,
                'weight' => 2.5,
                'length' => 20.0,
                'width' => 13.0,
                'height' => 15.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
            // Books - Non-Fiction
            [
                'sku' => 'BOOK-002',
                'ean' => '1234567890161',
                'model' => 'Business Book',
                'name' => 'Atomic Habits - James Clear',
                'description' => 'Carte despre formarea de obiceiuri bune si eliminarea celor rele.',
                'short_description' => 'Atomic Habits - James Clear',
                'price_ron' => 59.99,
                'purchase_price_ron' => 30.00,
                'stock_quantity' => 60,
                'weight' => 0.4,
                'length' => 21.0,
                'width' => 14.0,
                'height' => 2.0,
                'main_image_url' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop&q=80',
                'status' => true,
            ],
        
        ];
        
        return $products;
    }
}
